# Generated by Django 4.2.5 on 2023-09-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=23, max_length=200),
            preserve_default=False,
        ),
    ]
